ports:
  - name: /dev/ttyUSB1
    baudrate: 115200
    parity: 0 #Not Implemented yet.
    desc: Testing-1
    status: 1 #1-Enable 2-Disable on UI.
  - name: /dev/ttyUSB2
    baudrate: 115200
    parity: 0
    desc: Testing-2
    status: 2 #1-Enable 2-Disable on UI.
  - name: /dev/ttyUSB3
    baudrate: 115200
    parity: 0 #Not implemented yet.
    desc: Testing-3
    status: 1
logs:
  inlogs: /var/serial-port-websocket/logs/
  maxsize: 20 #Megabytes
  maxbackups: 10 #Number of Files
  maxage: 30 #Number of Days
serverconfig:
  - name: http
    enable: 1 #1-Enable 2-Disable
    port: 8083
    sslcert: na
    sslkey: na
  - name: https
    enable: 1 #1-Enable 2-Disable
    port: 8084
    sslcert: /etc/serial-port-websocket/server.crt
    sslkey: /etc/serial-port-websocket/server.key
